apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: httpbin
  app.kubernetes.io/part-of: homelab-apps

namespace: homelab-apps
